name: Benchmark Runner
on:
  push:
    branches: ["experimental"]

jobs:
  geekbench:
    runs-on: ubuntu-latest
    steps:
      - name: Download Geekbench 6
        run: |
          wget https://cdn.geekbench.com/Geekbench-6.5.0-Linux.tar.gz
          tar xf Geekbench-6.5.0-Linux.tar.gz
          chmod +x Geekbench-6.5.0-Linux/geekbench6

      - name: Run Geekbench 6 (Free version)
        run: |
          cd Geekbench-6.5.0-Linux
          ./geekbench6 --cpu

      # Optionally, you can save the logs as an artifact
      - name: Save Geekbench logs
        uses: actions/upload-artifact@v4
        with:
          name: geekbench-logs
          path: Geekbench-6.5.0-Linux/output.log