version: 2
updates:
  # Maintain GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "experimental"
    labels:
      - "dependencies"
      - "github_actions"

  # Maintain Docker dependencies (Dockerfiles)
  - package-ecosystem: "docker"
    directory: "/" # Adjust this if your Dockerfile is in a subfolder like /docker
    schedule:
      interval: "daily"
    target-branch: "experimental"
    labels:
      - "dependencies"
      - "docker"
    # Optional: If you want to limit the number of open PRs